name: Deployment Pipeline

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            # - name: Lint
            #   run: npm run lint
            # - name: Test
            #   run: npm run test
            # - name: E2E tests
            #   with:
            #   command: npm run test:e2e
            #   start: npm run start
            #   wait-on: 'http://localhost:3000'
            # - name: Build
            #   run: npm run build
            # - name: Deploy
            #   uses: peaceiris/actions-gh-pages@v3
            #   with:
            #       github_token: ${{ secrets.GITHUB_TOKEN }}
            #       publish_dir: ./build