name: Deployment Pipeline

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: Install dependencies
              run: pnpm install
            # - name: Lint
            #   run: pnpm run lint
            # - name: Build
            #   run: pnpm run build
            # - name: Deploy
            #   uses: peaceiris/actions-gh-pages@v3
            #   with:
            #       github_token: ${{ secrets.GITHUB_TOKEN }}
            #       publish_dir: ./build